// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOF8J4NdhAl0OaA7wHzUKhPXK49gIkOwg',
    appId: '1:307188946999:web:a1441ec88baf12886d87b2',
    messagingSenderId: '307188946999',
    projectId: 'circlestest4',
    authDomain: 'circlestest4.firebaseapp.com',
    databaseURL: 'https://circlestest4.firebaseio.com',
    storageBucket: 'circlestest4.appspot.com',
    measurementId: 'G-14R4KC4L47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLGi9H-noYor0I_n-wUpywcF5hILZO1_0',
    appId: '1:307188946999:android:654facd67172ab3a6d87b2',
    messagingSenderId: '307188946999',
    projectId: 'circlestest4',
    databaseURL: 'https://circlestest4.firebaseio.com',
    storageBucket: 'circlestest4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCux-BWXsvaNhXKBfxI3aVoJpUINapQE4Y',
    appId: '1:307188946999:ios:75ab0f843bc681f26d87b2',
    messagingSenderId: '307188946999',
    projectId: 'circlestest4',
    databaseURL: 'https://circlestest4.firebaseio.com',
    storageBucket: 'circlestest4.appspot.com',
    iosClientId: '307188946999-m78ikm1fqjf2aaa8vnf1m4g4799iqu4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.circle',
  );
}
